config/routes.rb
Rails.application.routes.draw do
  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'

  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  namespace :admins do
    resources :registrations, only: %i[edit new]
    resources :sessions, only: [:new]
  end

  namespace :admin do
    get 'out' => 'customers#out'
    resources :customers, only: [:index]
    resources :genres, only: %i[new index create edit update destroy]
  end

  devise_for :customers, controllers: {
    sessions: 'customer/sessions',
    registrations: 'customer/registrations'
  }

  namespace :customer do
    resources :posts, only: %i[index show edit update new create destroy]
    resources :customers, only: %i[show edit update destroy] do
      resources :favorites, only: [:index]
    end
    resources :favorites, only: %i[create destroy]
    resources :post_comments, only: %i[create destroy]
    resources :relationships, only: %i[create destroy]
    get 'favorite' => 'favorites#favorite'
    get 'following' => 'relationships#following'
    get 'follower' => 'relationships#follower'
    get 'out' => 'customers#out'
    get 'ranking' => 'posts#ranking'
    get 'search', to: 'posts#search'
    patch 'withdraw' => 'customers#withdraw'
    get 'unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    patch 'withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    put 'withdraw' => 'customers#withdraw'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htm

  root 'homes#top'
  get 'top' => 'homes#top'

  get 'homes/about', to: 'homes#about'

  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name,      presence: true
  validates :email,           presence: true,uniqueness: true
  # validates :password, presence: true, on: :create

  attachment :profile_image
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :customer
  has_many :favorited_custmers, through: :favorites, source: :post

  def follow(other_customer)
    relationships.find_or_create_by(follow_id: other_customer.id) unless self == other_customer
  end

  def unfollow(other_customer)
    relationship = relationships.find_by(follow_id: other_customer.id)
    relationship.destroy if relationship
  end

  def following?(other_customer)
    followings.include?(other_customer)

  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
    @customers = Customer.all.page(params[:page]).per(10)
  end

  private

  def customers_params
    params.require(:customer).permit(:first_name, :last_name, :postal_code, :residence, :phone_number, :email, :is_valid,
                                     :page)
  end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  before_action :authenticate_customer!

  def show
    @customer = Customer.find(params[:id])
    @relationship_followings = Relationship.where(customer_id: @customer.id)
    @followings = []
    @relationship_followings.each do |following|
      customer = Customer.find(following.follow_id)
      @followings.push(customer)
    end
    @posts = @customer.posts
    @profile_images = @customer.profile_image
    @post = Post.where(customer_id: params[:id]).last
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    flash[:success] = '登録情報を変更しました'
    redirect_to customer_customer_path(@customer.id)
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    flash[:notice] = 'ありがとうございました。またのご利用を心よりお待ちしております。'
    redirect_to new_customer_registration_path
  end

  def unsubscribe
    @customer = current_customer
  end

  def withdraw
    @customer = current_customer
    @customer.update(is_valid: false)
    reset_session
    redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code,
                                     :address, :telephone_number, :profile_image)
  end
end

app/controllers/customer/favorites_controller.rb
class Customer::FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    favorite = Favorite.new(post_id: @post.id, customer_id: current_customer.id)
    favorite.save
  end

  def destroy
    @post = Post.find(params[:id])
    favorite = Favorite.find_by(post_id: @post.id, customer_id: current_customer.id)
    favorite.destroy
  end

  def index
#    @customer = Customer.find(params[:customer_id])
    @favorites = Favorite.where(customer_id: params[:customer_id])
  end
end

app/controllers/customer/post_comments_controller.rb
class Customer::PostCommentsController < ApplicationController
  before_action :authenticate_customer!

  def create
    @post = Post.find(params[:post_comment][:post_id])
    @comment = current_customer.post_comments.build(comment_params)
    @comment.save
  end

  def destroy
    @comment = PostComment.find(params[:id])
    @comment.destroy
    @post = @comment.post
    flash[:danger] = 'コメントを削除しました'
  end

  private

  def comment_params
    params.require(:post_comment).permit(:comment, :customer_id, :post_id)
  end

end

app/controllers/customer/posts_controller.rb
class Customer::PostsController < ApplicationController
  before_action :authenticate_customer!
  before_action :baria_customer, only: %i[edit destroy update]
  before_action :set_q, only: %i[index new show create update edit destroy search]

  def index
    @posts = Post.page(params[:page]).per(8).order(created_at: :desc)
    # @posts = Post.includes(:favorited_custmers).sort { |a, b| b.favorited_custmers.size <=> a.favorited_custmers.size }
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.post_comments.order(created_at: :desc)
    @comment = current_customer.post_comments.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.start_time = DateTime.now
    @post.customer_id = current_customer.id
    if @post.save
      flash[:success] = '投稿にに成功しました'
      redirect_to customer_posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to customer_posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:danger] = '投稿を削除しました'
    redirect_to customer_posts_path
  end

  def search
    @results = @q.result
  end

  def ranking
    ids = Post.includes(:favorited_custmers).sort { |a, b| b.favorited_custmers.size <=> a.favorited_custmers.size }.pluck(:id)
    @posts = Post.where(id: ids).order_as_specified(id: ids).page(params[:page]).per(8)
  end

  private

  def post_params
    params.require(:post).permit(:image, :name, :introduction, :genre_id, :post_image, :customer_id)
  end

  def set_q
    @q = Post.ransack(params[:q])
  end

  def baria_customer
    redirect_to top_path unless Post.find(params[:id]).customer_id == current_customer.id
  end
end

app/controllers/customer/registrations_controller.rb
class Customer::RegistrationsController < Devise::RegistrationsController
  def new
    @customer = Customer.new
  end

end

app/controllers/customer/relationships_controller.rb
class Customer::RelationshipsController < ApplicationController
  before_action :set_customer, only: %i[create destroy]

  def create
    @post = Post.find(params[:post_id])
    following = current_customer.follow(@customer)
    flash[:success] = 'ユーザーをフォローしました'
  end

  def destroy
    @post = Post.find(params[:post_id])
    following = current_customer.unfollow(@customer)
    following.destroy
    flash[:success] = 'ユーザーのフォローを解除しました'
  end

  def follower
    @followers = current_customer.reverse_of_relationships
  end

  def following
    @relationship_followings = Relationship.where(customer_id: current_customer.id)
    @followings = []
    @relationship_followings.each do |following|
      customer = Customer.find(following.follow_id)
      @followings.push(customer)
    end
  end

  private

  def relationship_params
    params.require(:relationship).permit(:follow_id)
  end

  def set_customer
    @customer = Customer.find(params[:follow_id])
  end
end

app/controllers/customer/sessions_controller.rb
class Customer::SessionsController < Devise::SessionsController
  before_action :reject_inactive_customer, only: [:create]

  def reject_inactive_customer
    @customer = Customer.find_by(email: params[:customer][:email])
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && !@customer.is_valid
        redirect_to new_customer_session_path
      end
    end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/favorites_helper.rb
module Customer::FavoritesHelper
end

app/helpers/customer/posts_comments_helper.rb
module Customer::PostsCommentsHelper
end

app/helpers/customer/posts_helper.rb
module Customer::PostsHelper
end

app/helpers/customer/relationships_helper.rb
module Customer::RelationshipsHelper
end

app/views/customer/customers/edit.html.erb
<div class="container">
  <div class= "row">
    <div class= "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <div class= "font">会員編集</div>
      <%# if @post.errors.any? %>
        <%#= @post.errors.count %>
        <%# @post.errors.full_messages.each do |message| %>
        <%#= message %>
        <%# end %>
      <%# end %>
      <div class="customer_edit">
        <div class="customer_edit_list">
          <%= form_with model: @customer, url: customer_customer_path(@customer.id), method: :patch, local:true do |f| %>
            <%= attachment_image_tag @customer, :profile_image, :string, 60, 60, fallback: "no_image.jpg"%>
            <%= f.label :profile_image, "プロフィール画像" %><br />
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "edit_img" %>

            <div class="field">
              <%= f.label :last_name, "(性)" %><br />
              <%= f.text_field :last_name, autofocus: true %>
            </div>

            <div class="field">
              <%= f.label :first_name, "(名)" %><br />
              <%= f.text_field :first_name, autofocus: true %>
            </div>

            <div class="field">
              <%= f.label :last_name_kana, "(セイ)" %><br />
              <%= f.text_field :last_name_kana, autofocus: true %>
            </div>

            <div class="field">
              <%= f.label :first_name_kana, "(メイ)" %><br />
              <%= f.text_field :first_name_kana, autofocus: true %>
            </div>

            <div class="field">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
            </div>
            <div class="actions">
            <%= f.submit "Update", class: "customer_edit_button" %>
            </div>
            <% end %>
          <%= link_to "マイページに戻る", :back %>
        </div>
      </di>
    </div>
  </div>
</div>

app/views/customer/customers/show.html.erb
<%= render partial: 'layouts/flash' %>
<!--マイページ-->
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <P><%= attachment_image_tag @customer, :profile_image, format: 'jpeg', size: "300x300" , fallback: "no_image.jpg"%>
      <P>氏名 : <%= @customer.last_name %> <%= @customer.first_name %></P>
      <P>カナ : <%= @customer.last_name_kana %> <%= @customer.first_name_kana %></P>
      <% if @customer.id == current_customer.id %>
      <p><%= link_to "プロフィール編集", edit_customer_customer_path(@customer.id), class: "glyphicon glyphicon-pencil btn btn-success" %></p>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
        <%= month_calendar(events: Post.where(customer_id: params[:id])) do |date, posts| %>
          <%= date.day %>
          <% posts.each do |post| %>
          <div>
            <%=link_to post.name, customer_post_path(post) %>
          </div>
          <% end %>
        <% end %>
    </div>
  </div>
    <p>フォロー数:<%=link_to @followings.count, customer_following_path %></p>
    <p>フォロワー数:<%=link_to @customer.followers.count, customer_follower_path %></p>
    <p>いいね数:<%= link_to @customer.favorites.count, customer_customer_favorites_path(@customer) %></p>
</div>

app/views/customer/customers/unsubscribe.html.erb
<div class="container">
  <div class= "row">
    <div class= "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <div class= "font_withdrawal">本当に退会しますか？</div>
      <div class="font_withdrawal_list">
        <p>退会すると、会員情報や</br>
        いいねした投稿が閲覧できなくなります。</br>
        退会する場合は、「退会する」をクリックしてください。</br>
        <div class="withdrawal_button">
          <%= link_to "退会しない", customer_customer_path(current_customer), class: 'glyphicon glyphicon-home btn btn-primary' %>
          <%= link_to "退会する", customer_withdraw_customer_path, method: :patch, data: {confirm: "本当に退会してもよろしいですか？"}, class: "glyphicon glyphicon-tint btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
</div>