config/routes.rb
Rails.application.routes.draw do
  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'

  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  namespace :admins do
    resources :registrations, only: %i[edit new]
    resources :sessions, only: [:new]
  end

  namespace :admin do
    get 'out' => 'customers#out'
    resources :customers, only: [:index]
    resources :genres, only: %i[new index create edit update destroy]
  end

  devise_for :customers, controllers: {
    sessions: 'customer/sessions',
    registrations: 'customer/registrations'
  }

  namespace :customer do
    resources :posts, only: %i[index show edit update new create destroy]
    resources :customers, only: %i[show edit update destroy] do
      resources :favorites, only: [:index]
    end
    resources :favorites, only: %i[create destroy]
    resources :post_comments, only: %i[create destroy]
    resources :relationships, only: %i[create destroy]
    get 'favorite' => 'favorites#favorite'
    get 'following' => 'relationships#following'
    get 'follower' => 'relationships#follower'
    get 'out' => 'customers#out'
    get 'ranking' => 'posts#ranking'
    get 'search', to: 'posts#search'
    patch 'withdraw' => 'customers#withdraw'
    get 'unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    patch 'withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    put 'withdraw' => 'customers#withdraw'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htm

  root 'homes#top'
  get 'top' => 'homes#top'

  get 'homes/about', to: 'homes#about'

  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model
  attr_accessor :name, :email, :message

  define_model_callbacks :save
  before_save :form_validation
  validates :name, presence: { message: '名前を入力してください' }
  validates :email, presence: { message: 'メールアドレスを入力してください' }
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    @inquiry = Inquiry.new
    render action: 'index'
  end

  def confirm
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    if @inquiry.valid?
    #      # OK。確認画面を表示
    #    render :action => 'confirm'
    else
      # NG。入力画面を再表示
      #      render :action => 'index'
    end
  end

  def thanks
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    InquiryMailer.received_email(@inquiry).deliver
    # 完了画面を表示
    render action: 'thanks'
  end
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/views/inquiry/confirm.html.erb
<div class="page-header">
  <h1>お問い合わせ内容確認</h1>
</div>

<%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>
  <table class="table">
    <tr>
      <th>名前</th>
      <td>
        <%= f.hidden_field :name %>
        <%= @inquiry.name %>
      </td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td>
        <%= f.hidden_field :email %>
        <%= @inquiry.email %>
      </td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td>
        <%= f.hidden_field :message %>
        <%= simple_format(@inquiry.message) %>
      </td>
    </tr>
  </table>
  <div class="search_button_area">
    <%= f.submit '送信', class: "listen_button" %>
  </div>
<% end %>

app/views/inquiry/index.html.erb
<div class="container">
  <div class= "row">
    <div class= "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <div class= "search_font">お問い合わせ</div>
      <div class="search_text">
        <div class="search_host">
          <%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
            <% if @inquiry.errors.any? %>
              <div class="alert alert-danger" role="alert">
                <strong>入力内容にエラーがあります</strong>
                <ul>
                  <% @inquiry.errors.each do |attr, msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <table class="table">
              <tr>
                <th>名前<span class="text-danger">（必須）</span></th>
                <td><%= f.text_field :name %></td>
              </tr>
              <tr>
                <th>メールアドレス<span class="text-danger">（必須）</span></th>
                <td><%= f.text_field :email %></td>
              </tr>
              <tr>
                <th>お問い合わせ内容<span class="text-danger">（必須）</span></th>
                <td><%= f.text_area :message %></td>
              </tr>
            </table>
            <div class="search_button_area">
              <%= f.submit '確認', class: 'search_button' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/inquiry/thanks.html.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
  <p>
    お問い合わせいただきありがとうございました。
  </p>
</div>