config/routes.rb
Rails.application.routes.draw do
  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'

  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  namespace :admins do
    resources :registrations, only: %i[edit new]
    resources :sessions, only: [:new]
  end

  namespace :admin do
    get 'out' => 'customers#out'
    resources :customers, only: [:index]
    resources :genres, only: %i[new index create edit update destroy]
  end

  devise_for :customers, controllers: {
    sessions: 'customer/sessions',
    registrations: 'customer/registrations'
  }

  namespace :customer do
    resources :posts, only: %i[index show edit update new create destroy]
    resources :customers, only: %i[show edit update destroy] do
      resources :favorites, only: [:index]
    end
    resources :favorites, only: %i[create destroy]
    resources :post_comments, only: %i[create destroy]
    resources :relationships, only: %i[create destroy]
    get 'favorite' => 'favorites#favorite'
    get 'following' => 'relationships#following'
    get 'follower' => 'relationships#follower'
    get 'out' => 'customers#out'
    get 'ranking' => 'posts#ranking'
    get 'search', to: 'posts#search'
    patch 'withdraw' => 'customers#withdraw'
    get 'unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    patch 'withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    put 'withdraw' => 'customers#withdraw'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htm

  root 'homes#top'
  get 'top' => 'homes#top'

  get 'homes/about', to: 'homes#about'

  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name,      presence: true
  validates :email,           presence: true,uniqueness: true
  # validates :password, presence: true, on: :create

  attachment :profile_image
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :customer
  has_many :favorited_custmers, through: :favorites, source: :post

  def follow(other_customer)
    relationships.find_or_create_by(follow_id: other_customer.id) unless self == other_customer
  end

  def unfollow(other_customer)
    relationship = relationships.find_by(follow_id: other_customer.id)
    relationship.destroy if relationship
  end

  def following?(other_customer)
    followings.include?(other_customer)

  end
end

app/models/post.rb
class Post < ApplicationRecord
  extend OrderAsSpecified
  validates :name, presence: true
  validates :introduction, presence: true
  validates :post_image, presence: true
  attachment :post_image

  belongs_to :customer
  belongs_to :genre
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_custmers, through: :favorites, source: :customer

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
    @customers = Customer.all.page(params[:page]).per(10)
  end

  private

  def customers_params
    params.require(:customer).permit(:first_name, :last_name, :postal_code, :residence, :phone_number, :email, :is_valid,
                                     :page)
  end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  before_action :authenticate_customer!

  def show
    @customer = Customer.find(params[:id])
    @relationship_followings = Relationship.where(customer_id: @customer.id)
    @followings = []
    @relationship_followings.each do |following|
      customer = Customer.find(following.follow_id)
      @followings.push(customer)
    end
    @posts = @customer.posts
    @profile_images = @customer.profile_image
    @post = Post.where(customer_id: params[:id]).last
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    flash[:success] = '登録情報を変更しました'
    redirect_to customer_customer_path(@customer.id)
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    flash[:notice] = 'ありがとうございました。またのご利用を心よりお待ちしております。'
    redirect_to new_customer_registration_path
  end

  def unsubscribe
    @customer = current_customer
  end

  def withdraw
    @customer = current_customer
    @customer.update(is_valid: false)
    reset_session
    redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code,
                                     :address, :telephone_number, :profile_image)
  end
end

app/controllers/customer/favorites_controller.rb
class Customer::FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    favorite = Favorite.new(post_id: @post.id, customer_id: current_customer.id)
    favorite.save
  end

  def destroy
    @post = Post.find(params[:id])
    favorite = Favorite.find_by(post_id: @post.id, customer_id: current_customer.id)
    favorite.destroy
  end

  def index
#    @customer = Customer.find(params[:customer_id])
    @favorites = Favorite.where(customer_id: params[:customer_id])
  end
end

app/controllers/customer/post_comments_controller.rb
class Customer::PostCommentsController < ApplicationController
  before_action :authenticate_customer!

  def create
    @post = Post.find(params[:post_comment][:post_id])
    @comment = current_customer.post_comments.build(comment_params)
    @comment.save
  end

  def destroy
    @comment = PostComment.find(params[:id])
    @comment.destroy
    @post = @comment.post
    flash[:danger] = 'コメントを削除しました'
  end

  private

  def comment_params
    params.require(:post_comment).permit(:comment, :customer_id, :post_id)
  end

end

app/controllers/customer/posts_controller.rb
class Customer::PostsController < ApplicationController
  before_action :authenticate_customer!
  before_action :baria_customer, only: %i[edit destroy update]
  before_action :set_q, only: %i[index new show create update edit destroy search]

  def index
    @posts = Post.page(params[:page]).per(8).order(created_at: :desc)
    # @posts = Post.includes(:favorited_custmers).sort { |a, b| b.favorited_custmers.size <=> a.favorited_custmers.size }
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.post_comments.order(created_at: :desc)
    @comment = current_customer.post_comments.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.start_time = DateTime.now
    @post.customer_id = current_customer.id
    if @post.save
      flash[:success] = '投稿にに成功しました'
      redirect_to customer_posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to customer_posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:danger] = '投稿を削除しました'
    redirect_to customer_posts_path
  end

  def search
    @results = @q.result
  end

  def ranking
    ids = Post.includes(:favorited_custmers).sort { |a, b| b.favorited_custmers.size <=> a.favorited_custmers.size }.pluck(:id)
    @posts = Post.where(id: ids).order_as_specified(id: ids).page(params[:page]).per(8)
  end

  private

  def post_params
    params.require(:post).permit(:image, :name, :introduction, :genre_id, :post_image, :customer_id)
  end

  def set_q
    @q = Post.ransack(params[:q])
  end

  def baria_customer
    redirect_to top_path unless Post.find(params[:id]).customer_id == current_customer.id
  end
end

app/controllers/customer/registrations_controller.rb
class Customer::RegistrationsController < Devise::RegistrationsController
  def new
    @customer = Customer.new
  end

end

app/controllers/customer/relationships_controller.rb
class Customer::RelationshipsController < ApplicationController
  before_action :set_customer, only: %i[create destroy]

  def create
    @post = Post.find(params[:post_id])
    following = current_customer.follow(@customer)
    flash[:success] = 'ユーザーをフォローしました'
  end

  def destroy
    @post = Post.find(params[:post_id])
    following = current_customer.unfollow(@customer)
    following.destroy
    flash[:success] = 'ユーザーのフォローを解除しました'
  end

  def follower
    @followers = current_customer.reverse_of_relationships
  end

  def following
    @relationship_followings = Relationship.where(customer_id: current_customer.id)
    @followings = []
    @relationship_followings.each do |following|
      customer = Customer.find(following.follow_id)
      @followings.push(customer)
    end
  end

  private

  def relationship_params
    params.require(:relationship).permit(:follow_id)
  end

  def set_customer
    @customer = Customer.find(params[:follow_id])
  end
end

app/controllers/customer/sessions_controller.rb
class Customer::SessionsController < Devise::SessionsController
  before_action :reject_inactive_customer, only: [:create]

  def reject_inactive_customer
    @customer = Customer.find_by(email: params[:customer][:email])
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && !@customer.is_valid
        redirect_to new_customer_session_path
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    post = post.new(post_params)
    post.save
    redirect_to '/posts_index_path'
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
  
  def post_params
    params.require(:post).permit(:image, :title, :body, :genre_id)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/favorites_helper.rb
module Customer::FavoritesHelper
end

app/helpers/customer/posts_comments_helper.rb
module Customer::PostsCommentsHelper
end

app/helpers/customer/posts_helper.rb
module Customer::PostsHelper
end

app/helpers/customer/relationships_helper.rb
module Customer::RelationshipsHelper
end

app/views/customer/posts/_comment.html.erb
<h2>コメントをする</h2>

  <%= form_with(model:[post, @comment], url: customer_post_comments_path, method: :post) do |f| %>
    <%= f.text_area :comment %>
    <%= f.hidden_field :post_id, value: post.id %>
    <%= f.submit 'コメントする' %>
  <% end %>
  <h2>コメント一覧</h2>
  <% @comments.each do |comment| %>
    <%= comment.comment %>
    <%= link_to "削除", customer_post_comment_path(comment.id), method: :delete, remote: true, data: {confirm: '本当に削除しますか？'} %>
  <% end %>

app/views/customer/posts/_follow.html.erb
<% unless @post.customer_id == current_customer.id %>
  <% if current_customer.following?(@post.customer) %>
    <%= form_with(model:@relationships, url: customer_relationship_path(@post.customer), method: :delete ) do |f| %>
     <%= f.hidden_field :follow_id, :value => @post.customer.id %>
     <%= f.hidden_field :post_id, value: @post.id %>
     <%= f.submit 'フォローを外す', class: 'btn btn-danger btn-block', remote: true %>
  <% end %>
  <% else %>
     <%= form_with(model:@relationship, url: customer_relationships_path) do |f| %>
     <%= f.hidden_field :follow_id, :value => @post.customer.id %>
     <%= f.hidden_field :post_id, value: @post.id %>
     <%= f.submit 'フォローする', class: 'btn btn-primary btn-block', remote: true %>
  <% end %>
  <% end %>
  <% end %>

app/views/customer/posts/_like.html.erb
<% if post.favorited_by?(current_customer) %>
  <p>
    <%= link_to customer_favorite_path(id: post.id, post_image_id: post.post_image_id), method: :delete, remote: true do %>
      ♥<%= post.favorites.count %> いいね
    <% end %>
  </p>
<% else %>
  <p>
    <%= link_to customer_favorites_path(post_id: post.id, post_image_id: post.post_image_id), method: :post, remote: true do %>
      ♡<%= post.favorites.count %> いいね
    <% end %>
  </p>
<% end %>

app/views/customer/posts/create.html.erb
<h1>Customer::Posts#create</h1>
<p>Find me in app/views/customer/posts/create.html.erb</p>

app/views/customer/posts/destroy.html.erb
<h1>Customer::Posts#destroy</h1>
<p>Find me in app/views/customer/posts/destroy.html.erb</p>

app/views/customer/posts/edit.html.erb
<div class="container">
  <div class= "row">
    <div class= "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>投稿編集</h1>
        <%= form_with model:@post, url: customer_post_path(@post), local: true do |f| %>
      <h4>投稿画像</h4>
        <%= f.attachment_field :post_image %>
      <h4>題名</h4>
        <%= f.text_field :name %>
      <h4>投稿内容</h4>
        <%= f.text_area :introduction %>
      <h4>ジャンル</h4>
        <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %>
        <%= f.submit '保存' %>
        <% end %>
    </div>
  </div>
</div>

app/views/customer/posts/index.html.erb
<%= render partial: 'layouts/flash' %>
<main>
  <h2 class="font">投稿一覧</h2>
  <!--検索機能-->
    <div class="search_text">
      <%= search_form_for @q, url: customer_search_path do |f| %>
      <%= f.label :genre_name_cont, '検索', class: "search_post"%>
      <%= f.search_field :genre_name_cont, placeholder: 'ジャンル検索', class: "search_host" %>
      <%= f.submit '検索', class: "search_button" %>
      <% end %>
    </div>
    <!--ランキング一覧遷移-->
    <div class="ranking_text">
      <i class="fas fa-crown">
        <%= link_to "ランキング", customer_ranking_path %>
      </i>
    </div>
  <div class="container">
    <div class="row">
      <% @posts.each do |post| %>
        <div class="col-md-3">
          <div class="post_index">
            <div class="post_index_list">
              <div><%= attachment_image_tag post, :post_image, format: 'jpeg', size: "200x200" , fallback: "no_image.jpg", class: "index_img" %></div>
              [<%= post.genre.try(:name) %>]
              <%= link_to post.name, customer_post_path(post) %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div>
  <%= paginate @posts %>
  </div>
</main>

app/views/customer/posts/new.html.erb
<div class="container">
  <div class= "row">
    <div class= "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <div class= "font">新規投稿</div>
      <% if @post.errors.any? %>
        <%= @post.errors.count %>件のエラーが発生しました
        <% @post.errors.full_messages.each do |message| %>
        <%= message %>
        <% end %>
      <% end %>
      <div class="post_new">
        <div class="form-register">
          <%= form_with model: @post, url:customer_posts_path, local:true do |f| %>
            <h6>投稿画像</h6>
            <div class="new_post"><%= f.attachment_field :post_image %></div><br>
            <h6>ジャンル</h6>
            <div class="new_genre"><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %></div><br>
            <div class="new_title"><%= f.text_field :name, placeholder: '題名' %></div><br>
            <div class=new_contents""><%= f.text_area :introduction, size: "2x5", class: "form-control", placeholder: '投稿内容' %></div><br>
            <div><%= f.submit '投稿', class: "button" %></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/customer/posts/ranking.html.erb
<main>
<h2 class="font">ランキング一覧</h2>
  <div class="container">
    <div class="row">
      <% @posts.each do |post| %>
        <div class="col-3">
          <div class="ranking_index">
            <div class="ranking_index_list">
              <%= attachment_image_tag post, :post_image, format: 'jpeg', size: "200x200" , fallback: "no_image.jpg", class: "ranking_index_img" %></br>
              [<%= link_to post.name, customer_post_path(post) %>]
              <%= post.genre.try(:name) %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
   <%= paginate @posts %>
  </div>
</main>

app/views/customer/posts/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <table class="table">
        <thead>
          <tr>
            <th>プロフィール画像</th>
            <th>お題</th>
            <th>ジャンル名</th>
          </tr>
        </thead>
        <% @results.each do |post| %>
        <tbody>
          <tr>
            <td><%= attachment_image_tag post, :post_image, format: 'jpeg', size: "100x100" , fallback: "no_image.jpg" %></td>
            <td><%= link_to post.name, customer_post_path(post) %></td>
            <td><%= post.genre.name %></td>
          </tr>
        </tbody>
        <% end %>
        <%= link_to "投稿一覧", customer_posts_path %>
      </table>
    </div>
  </div>
</div>

app/views/customer/posts/show.html.erb
<%= render partial: 'layouts/flash' %>
<!--<div class="test">-->
<!--</div>-->
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <%= attachment_image_tag @post, :post_image, format: 'jpeg', size: "400x200" , fallback: "no_image.jpg" %>
          <h1 class="blog_post_title">
            [<%= @post.genre.try(:name) %>] <%= @post.name %>
          </h1>
            <P><%= @post.introduction %></P>
          <% if @post.customer_id == current_customer.id %>
            <%= link_to '編集', edit_customer_post_path(@post) %>
            <%= link_to "削除", customer_post_path(@post), method: :delete, data: {confirm: '本当に削除しますか？'} %>
          <% end %>
        <!--フォロー機能-->
        <div class="follow_<%= @post.id %>">
          <%= render 'customer/posts/follow', post: @post %>
        </div>
        <!--いいね機能-->
        <div class="post_<%= @post.id %>">
          <%= render 'customer/posts/like', post: @post %>
        </div>
        <P><%= link_to "投稿者マイページ", customer_customer_path(@post.customer) %></P>
        <!--コメント機能-->
        <div class="comments">
          <%= render 'customer/post_comments/comment', post: @post %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/customer/posts/update.html.erb
<h1>Customer::Posts#update</h1>
<p>Find me in app/views/customer/posts/update.html.erb</p>