config/routes.rb
Rails.application.routes.draw do
  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'

  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  namespace :admins do
    resources :registrations, only: %i[edit new]
    resources :sessions, only: [:new]
  end

  namespace :admin do
    get 'out' => 'customers#out'
    resources :customers, only: [:index]
    resources :genres, only: %i[new index create edit update destroy]
  end

  devise_for :customers, controllers: {
    sessions: 'customer/sessions',
    registrations: 'customer/registrations'
  }

  namespace :customer do
    resources :posts, only: %i[index show edit update new create destroy]
    resources :customers, only: %i[show edit update destroy] do
      resources :favorites, only: [:index]
    end
    resources :favorites, only: %i[create destroy]
    resources :post_comments, only: %i[create destroy]
    resources :relationships, only: %i[create destroy]
    get 'favorite' => 'favorites#favorite'
    get 'following' => 'relationships#following'
    get 'follower' => 'relationships#follower'
    get 'out' => 'customers#out'
    get 'ranking' => 'posts#ranking'
    get 'search', to: 'posts#search'
    patch 'withdraw' => 'customers#withdraw'
    get 'unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    patch 'withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    put 'withdraw' => 'customers#withdraw'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htm

  root 'homes#top'
  get 'top' => 'homes#top'

  get 'homes/about', to: 'homes#about'

  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name,      presence: true
  validates :email,           presence: true,uniqueness: true
  # validates :password, presence: true, on: :create

  attachment :profile_image
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :customer
  has_many :favorited_custmers, through: :favorites, source: :post

  def follow(other_customer)
    relationships.find_or_create_by(follow_id: other_customer.id) unless self == other_customer
  end

  def unfollow(other_customer)
    relationship = relationships.find_by(follow_id: other_customer.id)
    relationship.destroy if relationship
  end

  def following?(other_customer)
    followings.include?(other_customer)

  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :customer
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true
  
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model
  attr_accessor :name, :email, :message

  define_model_callbacks :save
  before_save :form_validation
  validates :name, presence: { message: '名前を入力してください' }
  validates :email, presence: { message: 'メールアドレスを入力してください' }
end

app/models/post.rb
class Post < ApplicationRecord
  extend OrderAsSpecified
  validates :name, presence: true
  validates :introduction, presence: true
  validates :post_image, presence: true
  attachment :post_image

  belongs_to :customer
  belongs_to :genre
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_custmers, through: :favorites, source: :customer

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :customer
  belongs_to :post

  # validates :content, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :customer
  belongs_to :follow, class_name: 'Customer', foreign_key: "follow_id"
  validates :customer_id, presence: true
  validates :follow_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :authenticate_customer!


  def index
    @search = Customer.ransack(params[:q])
    @customers = @search.result
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: %i[last_name first_name last_name_kana first_name_kana postal_code address telephone_number
                                               is_valid profile_image])
  end

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      if customer_signed_in?
        sign_out(current_customer)
      end
      admin_customers_path
    when Customer
      if admin_signed_in?
        sign_out(current_admin)
      end
      customer_customer_path(current_customer)
    end
  end

  def after_sign_out_path_for(_resource)
    new_customer_session_path
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_q, only: %i[top about]

  def top
    @q = Customer.search(params[:q])
    @results = @q.result(distinct: true)
    @posts = Post.page(params[:page]).per(8).order(created_at: :desc)
  end

  def about; end

  def set_q
    @q = Post.ransack(params[:q])
  end
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    @inquiry = Inquiry.new
    render action: 'index'
  end

  def confirm
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    if @inquiry.valid?
    #      # OK。確認画面を表示
    #    render :action => 'confirm'
    else
      # NG。入力画面を再表示
      #      render :action => 'index'
    end
  end

  def thanks
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    InquiryMailer.received_email(@inquiry).deliver
    # 完了画面を表示
    render action: 'thanks'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    post = post.new(post_params)
    post.save
    redirect_to '/posts_index_path'
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
  
  def post_params
    params.require(:post).permit(:image, :title, :body, :genre_id)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer/favorites_helper.rb
module Customer::FavoritesHelper
end

app/helpers/customer/posts_helper.rb
module Customer::PostsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
    <p class="alert alert-<%= key %>">
      <%= value %><button type="button" class="close" data-dismiss="alert">&times;</button>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/5.3.7/css/swiper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/5.3.7/js/swiper.min.js"></script>
  </head>

  <!--会員側のheader-->
  <body>
    <header>
      <div class= "header-top-content">
        <%= link_to top_path, class:"header-title" do %>
          <i class="fas fa-heartbeat">S.Frail</i>
        <% end %>

      <div class= "header-inner">
        <nav class= "global_nav global_nav_pc">
            <ul class="page_nav">
              <% if customer_signed_in? %>
              <li>
                <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: "logout" %>
              </li>
              <li>
                <%= link_to "top", top_path, class: "top" %>
              </li>
              <li>
                <%= link_to 'マイページ', customer_customer_path(current_customer), class: "myapge" %>
              </li>
              <li>
                <%= link_to '新規投稿', new_customer_post_path, class: "newpost" %>
              </li>
              <li>
                <%= link_to '投稿一覧', customer_posts_path, class: "post" %>
              </li>
              <li>
                <%= link_to 'サイト概要', homes_about_path, class: "about" %>
              </li>
              <li>
                <%= link_to "お問い合わせ", inquiry_path, class: "inquiry" %>
              </li>
              <li>
                <%= link_to "管理者", admin_session_path, class: "admin" %>
              </li>
              <li>
                <%= link_to "退会", customer_confirm_unsubscribe_path, class: "unsubscribe" %>
              </li>
              <% elsif admin_signed_in? %>
              <li>
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "logout" %>
              </li>
              <li>
                <%= link_to "ジャンル", admin_genres_path, class: "genre" %>
              </li>
              <li>
                <%= link_to "会員一覧", admin_customers_path, class: "customer" %>
              </li>
              <% else %>
              <li>
                <%= link_to "新規登録", new_customer_registration_path, class: "signup" %>
              </li>
              <li>
                <%= link_to "ログイン", new_customer_session_path, class: "login" %>
              </li>
              <li>
                <%= link_to "topページ", top_path, class: "top" %>
              </li>
              <% end %>
            </ul>
        </nav>
        </div>
        </div>
        <div class="centering_parent">
          <p class="header-center sample-title">〜健康寿命に革命を〜</p>
        </div>
    </header>
      <%= yield %>
    <footer class="clearfix">
      <p class="footer-text">© All rights reserved by Infratop.Inc.</p>
    </footer>
  </body>
</html>